# Generated by Django 4.2.5 on 2023-09-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_typewriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='typewriter',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
