# Generated by Django 4.2.5 on 2023-09-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_skill_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
