# Generated by Django 4.2.5 on 2023-09-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='subject',
            field=models.CharField(choices=[('A', 'APP'), ('W', 'WEB'), ('C', 'CARD')], max_length=3, null=True),
        ),
    ]
